### ISSUE TITLE
jdk 12 not supported

### ISSUE THREAD

**Issue by gorrus** [JetBrains/jdk-sa-jdwp#2]
Exception in thread "main" java.lang.NoSuchMethodError: sun.jvm.hotspot.runtime.VM.getSymbolTable()Lsun/jvm/hotspot/memory/SymbolTable;
	at com.jetbrains.sa.jdi.VirtualMachineImpl.init(VirtualMachineImpl.java:179)
	at com.jetbrains.sa.jdi.VirtualMachineImpl.createVirtualMachineForPID(VirtualMachineImpl.java:215)
	at com.jetbrains.sa.SaJdwpUtils.createVirtualMachine(SaJdwpUtils.java:29)
	at com.jetbrains.sa.SaJdwpAttachingServer.main(SaJdwpAttachingServer.java:38)

**Comment by gorrus** [comment]
also in memory view:
Exception in thread "main" java.lang.NoSuchMethodError: sun.jvm.hotspot.oops.ObjectHeap.getBoolArrayKlassObj()Lsun/jvm/hotspot/oops/TypeArrayKlass;
	at com.jetbrains.sa.jdi.CompatibilityHelper10.allClasses(CompatibilityHelper10.java:130)
	at com.jetbrains.sa.jdi.VirtualMachineImpl.retrieveAllClasses(VirtualMachineImpl.java:310)
	at com.jetbrains.sa.jdi.VirtualMachineImpl.allClasses(VirtualMachineImpl.java:265)
	at com.jetbrains.sa.jdwp.JDWP$VirtualMachine$AllClassesWithGeneric.reply(JDWP.java:964)
	at com.jetbrains.sa.jdwp.JDWPProxy.reply(JDWPProxy.java:71)
	at com.jetbrains.sa.SaJdwpAttachingServer.main(SaJdwpAttachingServer.java:62)

**Comment by gorrus** [comment]
fixed the first exception, but allClasses still does not work
