### ISSUE TITLE
IllegalStateException from objectMirror

### ISSUE THREAD

**Issue by gorrus** [JetBrains/jdk-sa-jdwp#3]
java.lang.IllegalStateException: Object with id 68 not found
	at com.jetbrains.sa.jdi.VirtualMachineImpl.objectMirror(VirtualMachineImpl.java:634)
	at com.jetbrains.sa.jdwp.JDWP$ObjectReference$GetValues.reply(JDWP.java:2515)
	at com.jetbrains.sa.jdwp.JDWPProxy.reply(JDWPProxy.java:71)
	at com.jetbrains.sa.SaJdwpListeningServer.main(SaJdwpListeningServer.java:64)

**Comment by gorrus** [comment]
our implementation of objectMirror(long) can not "resurrect" objects that were removed from the cache
